collections.push({
    id: "bible",
    title: "Bible (CSB)",
    category: "read",
    profiles: [
        profiles.BRETT
    ],
    entries: [
        { id: "genesis", title: "Genesis", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "exodus", title: "Exodus", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "leviticus", title: "Leviticus", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "numbers", title: "Numbers", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "deuteronomy", title: "Deuteronomy", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "joshua", title: "Joshua", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "judges", title: "Judges", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "ruth", title: "Ruth", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "1Samuel", title: "1 Samuel", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "2Samuel", title: "2 Samuel", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "1Kings", title: "1 Kings", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "2Kings", title: "2 Kings", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "1Chronicles", title: "1 Chronicles", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "2Chronicles", title: "2 Chronicles", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "ezra", title: "Ezra", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "nehemiah", title: "Nehemiah", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "esther", title: "Esther", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "job", title: "Job", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "psalms", title: "Psalms", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "proverbs", title: "Proverbs", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "ecclesiastes", title: "Ecclesiastes", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "songOfSongs", title: "Song of Songs", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "isaiah", title: "Isaiah", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "jeremiah", title: "Jeremiah", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "lamentations", title: "Lamentations", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "ezekiel", title: "Ezekiel", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "daniel", title: "Daniel", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "hosea", title: "Hosea", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "joel", title: "Joel", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "amos", title: "Amos", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "obadiah", title: "Obadiah", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "jonah", title: "Jonah", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "micah", title: "Micah", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "nahum", title: "Nahum", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "habakkuk", title: "Habakkuk", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "zephaniah", title: "Zephaniah", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "haggai", title: "Haggai", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "zechariah", title: "Zechariah", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "malachi", title: "Malachi", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "matthew", title: "Matthew", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "mark", title: "Mark", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "luke", title: "Luke", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "john", title: "John", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "acts", title: "Acts", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "romans", title: "Romans", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "1Corinthians", title: "1 Corinthians", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "2Corinthians", title: "2 Corinthians", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "galatians", title: "Galatians", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "ephesians", title: "Ephesians", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "philippians", title: "Philippians", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "colossians", title: "Colossians", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "1Thessalonians", title: "1 Thessalonians", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "2Thessalonians", title: "2 Thessalonians", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "1Timothy", title: "1 Timothy", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "2Timothy", title: "2 Timothy", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "titus", title: "Titus", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "philemon", title: "Philemon", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "hebrews", title: "Hebrews", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "james", title: "James", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "1Peter", title: "1 Peter", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "2Peter", title: "2 Peter", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "1John", title: "1 John", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "2John", title: "2 John", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "3John", title: "3 John", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "jude", title: "Jude", type: EntryType.BOOK, status: Status.NOT_STARTED },
        { id: "revelation", title: "Revelation", type: EntryType.BOOK, status: Status.NOT_STARTED }
    ]
});
